In [20]:
import pandas as pd

In [21]:
ogrenciler = {
    "isim":["Ali","veli"],
    "not":[10,20],
    "yas":[22,24]
}

In [22]:
ogrenciler

{'isim': ['Ali', 'veli'], 'not': [10, 20], 'yas': [22, 24]}

In [23]:
a = pd.DataFrame(ogrenciler)

In [24]:
a

   isim  not  yas
0   Ali   10   22
1  veli   20   24

In [25]:
a.iloc[1,2]

np.int64(24)

In [26]:
a.T

        0     1
isim  Ali  veli
not    10    20
yas    22    24

In [27]:
sozluk = {
    "isim" : ["Ali","Ahmet","Mehmet","Veli","Arda","Doruk"],
    "ara sinav" : [5,54,12,22,15,87],
    "odev" : [68,44,87,74,68,70],
    "final" : [55,64,77,88,100,90]
}

In [28]:
dataFrame = pd.DataFrame(sozluk)

In [29]:
dataFrame

     isim  ara sinav  odev  final
0     Ali          5    68     55
1   Ahmet         54    44     64
2  Mehmet         12    87     77
3    Veli         22    74     88
4    Arda         15    68    100
5   Doruk         87    70     90

In [30]:
dataFrame["ortalama"] = dataFrame['ara sinav']*0.25 + dataFrame['odev']*0.25 + dataFrame['final']*0.5

In [31]:
dataFrame

     isim  ara sinav  odev  final  ortalama
0     Ali          5    68     55     45.75
1   Ahmet         54    44     64     56.50
2  Mehmet         12    87     77     63.25
3    Veli         22    74     88     68.00
4    Arda         15    68    100     70.75
5   Doruk         87    70     90     84.25

In [32]:
dataFrame['yeni sutun'] = [0,1,2,3,4,5]

In [33]:
dataFrame

     isim  ara sinav  odev  final  ortalama  yeni sutun
0     Ali          5    68     55     45.75           0
1   Ahmet         54    44     64     56.50           1
2  Mehmet         12    87     77     63.25           2
3    Veli         22    74     88     68.00           3
4    Arda         15    68    100     70.75           4
5   Doruk         87    70     90     84.25           5

In [34]:
maasSozlugu = {"Departman" : ["Yazilim","Yazilim","Pazarlama","Pazarlama","Hukuk","Hukuk"],
               "Calisan Ismi" : ["Ahmet","Mehmet","Atil","Burak","Zeynep","Fatma"],
               "Maas" : [100,150,200,300,400,500]}

In [35]:
b = pd.DataFrame(maasSozlugu)

In [36]:
b

   Departman Calisan Ismi  Maas
0    Yazilim        Ahmet   100
1    Yazilim       Mehmet   150
2  Pazarlama         Atil   200
3  Pazarlama        Burak   300
4      Hukuk       Zeynep   400
5      Hukuk        Fatma   500

In [37]:
c = b.groupby("Departman")

In [38]:
a

   isim  not  yas
0   Ali   10   22
1  veli   20   24

In [39]:
b

   Departman Calisan Ismi  Maas
0    Yazilim        Ahmet   100
1    Yazilim       Mehmet   150
2  Pazarlama         Atil   200
3  Pazarlama        Burak   300
4      Hukuk       Zeynep   400
5      Hukuk        Fatma   500

In [50]:
b.loc[[0,2,4],["Calisan Ismi"]]

  Calisan Ismi
0        Ahmet
2         Atil
4       Zeynep

In [73]:
sozlukWine = {"wine_1" : [1,2,3],
              "country" : ["Turkey","Australia","New Zealand"],
              "wine_3" : [7,8,9]}

In [74]:
wineDF = pd.DataFrame(sozlukWine)

In [75]:
wineDF

   wine_1      country  wine_3
0       1       Turkey       7
1       2    Australia       8
2       3  New Zealand       9

In [102]:
deneme = ((wineDF.country == "Australia") | (wineDF.country == "New Zealand")) & (wineDF.wine_3 > 5)

In [103]:
deneme

0    False
1     True
2     True
dtype: bool