In [49]:
import numpy as np
import pandas as pd

In [50]:
data = np.random.randn(4,3)

In [51]:
data

array([[ 0.34835965, -1.32468857, -2.12621456],
       [ 0.74811538,  1.01293434, -0.6327204 ],
       [ 1.2179313 ,  0.01486869, -0.01399961],
       [ 0.36889707,  1.35825134, -1.13855765]])

In [52]:
dataFrame = pd.DataFrame(data) #excel tablosunun python hali gibidir

In [53]:
dataFrame

          0         1         2
0  0.348360 -1.324689 -2.126215
1  0.748115  1.012934 -0.632720
2  1.217931  0.014869 -0.014000
3  0.368897  1.358251 -1.138558

In [54]:
dataFrame[0] #sutun olarak getirir (0 indexli sutun)

0    0.348360
1    0.748115
2    1.217931
3    0.368897
Name: 0, dtype: float64

In [55]:
yeniDataFrame = pd.DataFrame(data,index=["Atil","Zeynep","Atlas","Mehmet"],columns=["Maas","Yas","Calisma Saati"])

In [56]:
yeniDataFrame

            Maas       Yas  Calisma Saati
Atil    0.348360 -1.324689      -2.126215
Zeynep  0.748115  1.012934      -0.632720
Atlas   1.217931  0.014869      -0.014000
Mehmet  0.368897  1.358251      -1.138558

###Sutun(column) getirme

In [57]:
yeniDataFrame["Yas"] #Yas sutununu getir

Atil     -1.324689
Zeynep    1.012934
Atlas     0.014869
Mehmet    1.358251
Name: Yas, dtype: float64

In [58]:
yeniDataFrame["Calisma Saati"] #Calisma Saati sutununu getir

Atil     -2.126215
Zeynep   -0.632720
Atlas    -0.014000
Mehmet   -1.138558
Name: Calisma Saati, dtype: float64

In [59]:
yeniDataFrame[["Maas","Yas"]] #Maas ve Yas sutununu getirir

            Maas       Yas
Atil    0.348360 -1.324689
Zeynep  0.748115  1.012934
Atlas   1.217931  0.014869
Mehmet  0.368897  1.358251

###satir(row) getirme **loc**

In [60]:
yeniDataFrame.loc["Atil"] #loc = location

Maas             0.348360
Yas             -1.324689
Calisma Saati   -2.126215
Name: Atil, dtype: float64

In [61]:
yeniDataFrame.loc["Zeynep"]

Maas             0.748115
Yas              1.012934
Calisma Saati   -0.632720
Name: Zeynep, dtype: float64

In [62]:
yeniDataFrame.loc["Atil"]["Yas"]

np.float64(-1.3246885735274632)

In [63]:
yeniDataFrame.loc["Atlas","Yas"]

np.float64(0.014868692582928797)

###Index bazli location **iloc**

In [64]:
yeniDataFrame.iloc[1] #iloc = index location #1 indexli satir row gelir

Maas             0.748115
Yas              1.012934
Calisma Saati   -0.632720
Name: Zeynep, dtype: float64

###yeni sutun column ekleme

In [65]:
yeniDataFrame["Emeklilik Yasi"] = yeniDataFrame["Yas"] + yeniDataFrame["Yas"]

In [66]:
yeniDataFrame

            Maas       Yas  Calisma Saati  Emeklilik Yasi
Atil    0.348360 -1.324689      -2.126215       -2.649377
Zeynep  0.748115  1.012934      -0.632720        2.025869
Atlas   1.217931  0.014869      -0.014000        0.029737
Mehmet  0.368897  1.358251      -1.138558        2.716503

###sutun-satir silme

In [67]:
yeniDataFrame.drop("Emeklilik Yasi" , axis = 1 , inplace = True) #axis = 1 sutunlar #inplace = True ise islem kalici dataFrame degisir False ise gecici dataFrame degismez

In [68]:
yeniDataFrame.drop("Mehmet",axis = 0) #axis = 0 satirlar

            Maas       Yas  Calisma Saati
Atil    0.348360 -1.324689      -2.126215
Zeynep  0.748115  1.012934      -0.632720
Atlas   1.217931  0.014869      -0.014000

In [69]:
yeniDataFrame

            Maas       Yas  Calisma Saati
Atil    0.348360 -1.324689      -2.126215
Zeynep  0.748115  1.012934      -0.632720
Atlas   1.217931  0.014869      -0.014000
Mehmet  0.368897  1.358251      -1.138558

###Kosul

In [70]:
booleanFrame = yeniDataFrame < 0 #sifirdan kucuk olanlar True buyukler False

In [71]:
booleanFrame

         Maas    Yas  Calisma Saati
Atil    False   True           True
Zeynep  False  False           True
Atlas   False  False           True
Mehmet  False  False           True

In [72]:
yeniDataFrame[booleanFrame] #sadece True olanlar gorunur digerleri NaN olarak gorunur

        Maas       Yas  Calisma Saati
Atil     NaN -1.324689      -2.126215
Zeynep   NaN       NaN      -0.632720
Atlas    NaN       NaN      -0.014000
Mehmet   NaN       NaN      -1.138558

In [73]:
yeniDataFrame[yeniDataFrame["Yas"] > 0] #dataFrame'nin Yas sutununda sadece 0'dan buyuk olanlari al

            Maas       Yas  Calisma Saati
Zeynep  0.748115  1.012934      -0.632720
Atlas   1.217931  0.014869      -0.014000
Mehmet  0.368897  1.358251      -1.138558

In [74]:
yeniDataFrame[yeniDataFrame["Calisma Saati"] > 0]

Empty DataFrame
Columns: [Maas, Yas, Calisma Saati]
Index: []

###index degistirme

In [75]:
yeniDataFrame.reset_index()

    index      Maas       Yas  Calisma Saati
0    Atil  0.348360 -1.324689      -2.126215
1  Zeynep  0.748115  1.012934      -0.632720
2   Atlas  1.217931  0.014869      -0.014000
3  Mehmet  0.368897  1.358251      -1.138558

In [76]:
yeniIndexListesi = ["Ati","Zey","Atl","Meh"]

In [77]:
yeniDataFrame["Yeni Index"] = yeniIndexListesi

In [78]:
yeniDataFrame.set_index("Yeni Index",inplace=True) #index kolonu degisti

In [79]:
yeniDataFrame

                Maas       Yas  Calisma Saati
Yeni Index
Ati         0.348360 -1.324689      -2.126215
Zey         0.748115  1.012934      -0.632720
Atl         1.217931  0.014869      -0.014000
Meh         0.368897  1.358251      -1.138558

In [80]:
yeniDataFrame.loc["Ati"]

Maas             0.348360
Yas             -1.324689
Calisma Saati   -2.126215
Name: Ati, dtype: float64

###Multi Index

In [81]:
ilkIndexler = ["Simpson","Simpson","Simpson","South Park","South Park","South Park"]

In [82]:
icIndexler = ["Homer","Bart","Marge","Cartman","Kenny","Kyle"]

In [83]:
birlesmisIndex = list(zip(ilkIndexler,icIndexler))

In [84]:
birlesmisIndex = pd.MultiIndex.from_tuples(birlesmisIndex) #Grup + alt grup ilişkilerinde kullanilir

In [85]:
birlesmisIndex

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [102]:
cizgiFilmListesi = [[40,"A"],[10,"B"],[30,"C"],[9,"D"],[10,"E"],[11,"F"]]

In [103]:
cizgiFilmNumpyDizisi = np.array(cizgiFilmListesi)

In [104]:
cizgiFilmDataFrame = pd.DataFrame(cizgiFilmNumpyDizisi,index=birlesmisIndex,columns=["Yas","Meslek"])

In [117]:
cizgiFilmDataFrame

                   Yas Meslek
Film Adi   isim
Simpson    Homer    40      A
           Bart     10      B
           Marge    30      C
South Park Cartman   9      D
           Kenny    10      E
           Kyle     11      F

In [106]:
cizgiFilmDataFrame.loc["Simpson"]

      Yas Meslek
Homer  40      A
Bart   10      B
Marge  30      C

In [107]:
cizgiFilmDataFrame.loc["South Park"]

        Yas Meslek
Cartman   9      D
Kenny    10      E
Kyle     11      F

In [109]:
cizgiFilmDataFrame.loc["South Park"].loc["Kenny"]

Yas       10
Meslek     E
Name: Kenny, dtype: object

In [113]:
cizgiFilmDataFrame.index.names = ["Film Adi","isim"]

In [114]:
cizgiFilmDataFrame

                   Yas Meslek
Film Adi   isim
Simpson    Homer    40      A
           Bart     10      B
           Marge    30      C
South Park Cartman   9      D
           Kenny    10      E
           Kyle     11      F