In [ ]:
import pandas as pd
import numpy as np

In [ ]:
sozlukVerisi = {"Istanbul":[30,29,np.nan] , "Ankara":[20,np.nan,25] , "Izmır":[40,39,38]} #np.nan = not a number (veri yok)
havaDurumuDataFrame = pd.DataFrame(sozlukVerisi)

In [ ]:
havaDurumuDataFrame

   Istanbul  Ankara  Izmır
0      30.0    20.0     40
1      29.0     NaN     39
2       NaN    25.0     38

In [ ]:
havaDurumuDataFrame.dropna() #nan olan eksik veri olan satirlari veya sutunlari siler

   Istanbul  Ankara  Izmır
0      30.0    20.0     40

In [ ]:
havaDurumuDataFrame.dropna(axis=0) #axis=0 ise nan iceren satirlari siler

   Istanbul  Ankara  Izmır
0      30.0    20.0     40

In [ ]:
havaDurumuDataFrame.dropna(axis=1) #axis=1 ise nan iceren sutunlari siler

   Izmır
0     40
1     39
2     38

# Yeni Ornek

In [ ]:
yeniVeri = {"Istanbul":[30,29,np.nan] , "Ankara":[20,np.nan,25] , "Izmır":[40,39,38] , "Antalya":[45,np.nan,np.nan]} #np.nan = not a number (veri yok)
yeniDataFrame = pd.DataFrame(yeniVeri)

In [ ]:
yeniDataFrame

   Istanbul  Ankara  Izmır  Antalya
0      30.0    20.0     40     45.0
1      29.0     NaN     39      NaN
2       NaN    25.0     38      NaN

In [ ]:
yeniDataFrame.dropna(axis=1,thresh=2) #sutunlarda axis=1 , en az 2 tane NaN olmayan (dolu) varsa o satir kalir digerleri silinir thresh=2

   Istanbul  Ankara  Izmır
0      30.0    20.0     40
1      29.0     NaN     39
2       NaN    25.0     38

In [ ]:
yeniDataFrame.fillna(20) #NaN olan yerlerin hepsine 20 degerini koy

   Istanbul  Ankara  Izmır  Antalya
0      30.0    20.0     40     45.0
1      29.0    20.0     39     20.0
2      20.0    25.0     38     20.0

#groupby

In [ ]:
maasSozlugu = {"Departman" : ["Yazilim","Yazilim","Pazarlama","Pazarlama","Hukuk","Hukuk"],
               "Calisan Ismi" : ["Ahmet","Mehmet","Atil","Burak","Zeynep","Fatma"],
               "Maas" : [100,150,200,300,400,500]}

In [ ]:
maasDataFrame = pd.DataFrame(maasSozlugu)

In [ ]:
maasDataFrame

   Departman Calisan Ismi  Maas
0    Yazilim        Ahmet   100
1    Yazilim       Mehmet   150
2  Pazarlama         Atil   200
3  Pazarlama        Burak   300
4      Hukuk       Zeynep   400
5      Hukuk        Fatma   500

In [ ]:
grupObjesi = maasDataFrame.groupby("Departman") #her grup uzerinde islem yapmamizi saglar

In [ ]:
grupObjesi.count() #kac tane var

           Calisan Ismi  Maas
Departman
Hukuk                 2     2
Pazarlama             2     2
Yazilim               2     2

In [ ]:
grupObjesi["Maas"].mean() #her bir Departmanın ortalamasini bulur

Departman
Hukuk        450.0
Pazarlama    250.0
Yazilim      125.0
Name: Maas, dtype: float64

In [ ]:
grupObjesi.min() #her bir Departmanın en dusuk Maasli verisi

          Calisan Ismi  Maas
Departman
Hukuk            Fatma   400
Pazarlama         Atil   200
Yazilim          Ahmet   100

In [ ]:
grupObjesi.max() #her bir Departmanın en yuksek Maasli verisi

          Calisan Ismi  Maas
Departman
Hukuk           Zeynep   500
Pazarlama        Burak   300
Yazilim         Mehmet   150

In [ ]:
grupObjesi.describe() #her bir departmana ait bazi ozellikleri tek bir tabloda hesapliyor (std = standart sapma)

           Maas
          count   mean        std    min    25%    50%    75%    max
Departman
Hukuk       2.0  450.0  70.710678  400.0  425.0  450.0  475.0  500.0
Pazarlama   2.0  250.0  70.710678  200.0  225.0  250.0  275.0  300.0
Yazilim     2.0  125.0  35.355339  100.0  112.5  125.0  137.5  150.0