In [ ]:
import numpy as np
import pandas as pd

In [ ]:
sozluk1 = {"isim" : ["Ahmet","Mehmet","Zeynep","Atıl"],
          "Spor" : ["Kosu","Yuzme","Kosu","Basketbol"],
          "kalori" : [100,200,300,400]
          }

In [ ]:
dataFrame1 = pd.DataFrame(sozluk1)

In [ ]:
dataFrame1

     isim       Spor  kalori
0   Ahmet       Kosu     100
1  Mehmet      Yuzme     200
2  Zeynep       Kosu     300
3    Atıl  Basketbol     400

In [ ]:
sozluk2 = {"isim" : ["Osman","Levent","Atlas","Fatma"],
          "Spor" : ["Kosu","Yuzme","Kosu","Basketbol"],
          "kalori" : [200,100,50,300]
          }

In [ ]:
dataFrame2 = pd.DataFrame(sozluk2)

In [ ]:
dataFrame2

     isim       Spor  kalori
0   Osman       Kosu     200
1  Levent      Yuzme     100
2   Atlas       Kosu      50
3   Fatma  Basketbol     300

In [ ]:
sozluk3 = {"isim" : ["Ayse","Mahmut","Duygu","Nur"],
          "Spor" : ["Kosu","Yuzme","Badminton","Tenis"],
          "kalori" : [300,400,500,250]
          }

In [ ]:
dataFrame3 = pd.DataFrame(sozluk3)

In [ ]:
dataFrame3

     isim       Spor  kalori
0    Ayse       Kosu     300
1  Mahmut      Yuzme     400
2   Duygu  Badminton     500
3     Nur      Tenis     250

#Concenation

In [ ]:
pd.concat([dataFrame1,dataFrame2,dataFrame3],axis = 0) #dataFrame'leri birlestirir axis = 0 ise alt alta gelir axis = 1 ise alt alta gelir

     isim       Spor  kalori
0   Ahmet       Kosu     100
1  Mehmet      Yuzme     200
2  Zeynep       Kosu     300
3    Atıl  Basketbol     400
0   Osman       Kosu     200
1  Levent      Yuzme     100
2   Atlas       Kosu      50
3   Fatma  Basketbol     300
0    Ayse       Kosu     300
1  Mahmut      Yuzme     400
2   Duygu  Badminton     500
3     Nur      Tenis     250

#Merge

In [ ]:
mergeSozluk1 = {"Isim" : ["Ahmet","Mehmet","Zeynep","Atil"],
                "Spor" : ["Kosu","Yuzme","Kosu","Basketbol"]}

In [ ]:
mergeDataFrame1 = pd.DataFrame(mergeSozluk1)

In [ ]:
mergeDataFrame1

     Isim       Spor
0   Ahmet       Kosu
1  Mehmet      Yuzme
2  Zeynep       Kosu
3    Atil  Basketbol

In [ ]:
mergeSozluk2 = {"Isim" : ["Ahmet","Mehmet","Zeynep","Atil"],
                "Kalori" : [100,200,150,250]}

In [ ]:
mergeDataFrame2 = pd.DataFrame(mergeSozluk2)

In [ ]:
mergeDataFrame2

     Isim  Kalori
0   Ahmet     100
1  Mehmet     200
2  Zeynep     150
3    Atil     250

In [ ]:
pd.merge(mergeDataFrame1,mergeDataFrame2,on = "Isim") #ortak kolona gore eslestir (on ile ortak kolon adini belirtiriz)

     Isim       Spor  Kalori
0   Ahmet       Kosu     100
1  Mehmet      Yuzme     200
2  Zeynep       Kosu     150
3    Atil  Basketbol     250

In [ ]:
maasSozluk = {"Isimler" : ["Atil","Zeynep","Mehmet","Ahmet"],
              "Departman" : ["Yazilim","Satis","Pazarlama","Yazilim"],
              "Maas" : [200,300,400,500]}

In [ ]:
maasDataFrame = pd.DataFrame(maasSozluk)

In [ ]:
maasDataFrame

  Isimler  Departman  Maas
0    Atil    Yazilim   200
1  Zeynep      Satis   300
2  Mehmet  Pazarlama   400
3   Ahmet    Yazilim   500

In [ ]:
maasDataFrame["Departman"].unique() #sutundaki degerleri getirir (tekrar edenleri bir kere getirir)

array(['Yazilim', 'Satis', 'Pazarlama'], dtype=object)

In [ ]:
maasDataFrame["Departman"].nunique() #number of unique kac tane departman oldugunu bulur

3

In [ ]:
maasDataFrame["Departman"].value_counts() #hangi departmandan kac tane kisi oldugunu getirir

Departman
Yazilim      2
Satis        1
Pazarlama    1
Name: count, dtype: int64

In [ ]:
def bruttenNete(maas):
  return maas * 0.66

In [ ]:
maasDataFrame["Maas"].apply(bruttenNete) #her maas degerine bruttenNete fonksiyonunu uygula (0*66 ile carp)

0    132.0
1    198.0
2    264.0
3    330.0
Name: Maas, dtype: float64

In [ ]:
maasDataFrame.isnull() #bos deger var mı ? (true = bos deger) (false = bos degil)

   Isimler  Departman   Maas
0    False      False  False
1    False      False  False
2    False      False  False
3    False      False  False

In [ ]:
yeniBirVeri = {"Karakter Sinifi" : ["South Park","South Park","Simpson","Simpson","Simpson"],
               "Karakter Ismi" : ["Cartman","Kenny","Homer","Bart","Bart"],
               "Karakter Yas" : [9,10,50,20,10]}

In [ ]:
karakterDF = pd.DataFrame(yeniBirVeri)

In [ ]:
karakterDF

  Karakter Sinifi Karakter Ismi  Karakter Yas
0      South Park       Cartman             9
1      South Park         Kenny            10
2         Simpson         Homer            50
3         Simpson          Bart            20
4         Simpson          Bart            10

In [ ]:
karakterDF.pivot_table(values = "Karakter Yas",index = ["Karakter Sinifi","Karakter Ismi"],aggfunc=np.sum) #veriyi ozet tabloya donusturur (aggfunc = hangi hesap toplama,ortalama...)

/tmp/ipython-input-4283400191.py:1: FutureWarning: The provided callable <function sum at 0x7ddc6e63d760> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  karakterDF.pivot_table(values = "Karakter Yas",index = ["Karakter Sinifi","Karakter Ismi"],aggfunc=np.sum)

                               Karakter Yas
Karakter Sinifi Karakter Ismi
Simpson         Bart                     30
                Homer                    50
South Park      Cartman                   9
                Kenny                    10