In [5]:
import numpy as np
import pandas as pd

In [7]:
dataFrame = pd.read_excel("Maas.xlsx")

### 1. Colab UI (Kullanıcı Arayüzü) ile Yükleme

Bu en basit yöntemdir:

1. Sol taraftaki menüde **Dosyalar** (klasör simgesi) bölümüne tıklayın.
2. Ardından **Yükle** (yukarı ok simgesi) düğmesine tıklayın.
3. Yerel diskinizden `Maas.xlsx` dosyasını seçin ve yükleyin.

Bu yöntemle yüklenen dosyalar oturum sona erdiğinde silinir, bu yüzden her yeni oturumda tekrar yüklemeniz gerekebilir.

In [8]:
dataFrame

  Unnamed: 0  Maas   Yas  Departman
0       Atil   100  40.0    Yazilim
1     Zeynep   150  50.0      Satis
2     Mehmet   200  30.0        NaN
3      Ahmet    50  10.0  Pazarlama
4      Atlas   150   NaN     Finans
5      Fatma   200  25.0      Hukuk

In [10]:
doluDegerlerDataFrame = dataFrame.dropna() #NaN olanlari birakir

In [11]:
doluDegerlerDataFrame

  Unnamed: 0  Maas   Yas  Departman
0       Atil   100  40.0    Yazilim
1     Zeynep   150  50.0      Satis
3      Ahmet    50  10.0  Pazarlama
5      Fatma   200  25.0      Hukuk

In [13]:
doluDegerlerDataFrame.to_excel("yeniMaas.xlsx") #doluDegerlerDataFrame'ini excel dosyasina yazar

In [14]:
##read_csv
##to_csv
##format csv ise bunlar kullanilir