###Ders 1 Seriler

In [2]:
import numpy as np
import pandas as pd

In [3]:
sozluk = {"oguz":1 ,"ali":2 ,"zeynep":3}

In [4]:
pd.Series(sozluk)

oguz      1
ali       2
zeynep    3
dtype: int64

In [5]:
yaslar = [50,40,30]

In [6]:
isimler = ["oguz","ali","zeynep"]

In [7]:
pd.Series(yaslar)

0    50
1    40
2    30
dtype: int64

In [8]:
pd.Series(yaslar,isimler)

oguz      50
ali       40
zeynep    30
dtype: int64

In [9]:
pd.Series(data = yaslar,index = isimler)

oguz      50
ali       40
zeynep    30
dtype: int64

In [10]:
numpyDizisi = np.array([50,40,30])

In [11]:
numpyDizisi

array([50, 40, 30])

In [12]:
pd.Series(numpyDizisi)

0    50
1    40
2    30
dtype: int64

In [13]:
pd.Series(numpyDizisi,isimler)

oguz      50
ali       40
zeynep    30
dtype: int64

###Ders 2 Series Ozellikleri

In [15]:
pd.Series(["Atil","Atlas","Osman"],[1,2,3]) #indexleri degistirdik normalde indexler 0,1,2 seklinde

1     Atil
2    Atlas
3    Osman
dtype: object

In [16]:
yarismaSonucu = pd.Series([10,5,1],["Atil","Atlas","Osman"])

In [18]:
yarismaSonucu

Atil     10
Atlas     5
Osman     1
dtype: int64

In [19]:
yarismaSonucu2 = pd.Series([20,10,8],["Atil","Atlas","Osman"])

In [20]:
yarismaSonucu2

Atil     20
Atlas    10
Osman     8
dtype: int64

In [23]:
sonSonuc = yarismaSonucu + yarismaSonucu2

In [24]:
sonSonuc

Atil     30
Atlas    15
Osman     9
dtype: int64

In [25]:
farkliSeries = pd.Series([20,30,40,50],["a","b","c","d"])

In [26]:
farkliSeries2 = pd.Series([10,5,3,1],["a","c","f","g"])

In [28]:
farkliSeries + farkliSeries2 #ortak olan degerleri toplar (kesisenleri toplar)

a    30.0
b     NaN
c    45.0
d     NaN
f     NaN
g     NaN
dtype: float64

In [29]:
farkliSeries * farkliSeries2

a    200.0
b      NaN
c    200.0
d      NaN
f      NaN
g      NaN
dtype: float64